# fly.toml app configuration file generated for lab-fly on 2023-08-22T22:08:20-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lab-fly"
primary_region = "mia"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.2"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"
  APP_URL = "https://lab-fly.fly.dev"
  APP_DEBUG= "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
